#!/usr/bin/env python3
# QSpawn Quake MAP Creator
# Sheikh Nightshader

import os

def print_banner():
    banner = r"""

           .,o'       `o,.
         ,o8'           `8o.
        o8'               `8o
       o8:                 ;8o
      .88                   88.
      :88.                 ,88:
      `888                 888'
       888o   `888 888'   o888
       `888o,. `88 88' .,o888'
        `8888888888888888888'
          `888888888888888'
             `::88⛧88;:'
                88 88
                88 88
                `8 8'
           ⛧     ` '     ⛧

QSpawn Quake MAP Creator Beta 1.1 - Sheikh Nightshader
"""
    print(banner)

DEFAULT_TEXTURES = ["bricka2_2", "woodflr1_5", "sky1"]
DEFAULT_ITEMS = [
    "monster_army", "monster_zombie", "item_health",
    "ammo_bullets", "ammo_shells", "ammo_spikes", "ammo_rockets",
    "weapon_shotgun","weapon_nailgun","weapon_supernailgun","weapon_rocketlauncher","weapon_lightning"
]

def fmt_point(p):
    return f"{int(p[0])} {int(p[1])} {int(p[2])}"

def face_line(a,b,c,tex="bricka2_2",uoff=0,voff=0,rot=0,us=1,vs=1):
    return f"( {fmt_point(a)} ) ( {fmt_point(b)} ) ( {fmt_point(c)} ) {tex} {uoff} {voff} {rot} {us} {vs}"

def box_faces(minp,maxp,texture="bricka2_2"):
    x0,y0,z0 = minp
    x1,y1,z1 = maxp
    v000 = (x0,y0,z0); v100 = (x1,y0,z0); v110 = (x1,y1,z0); v010 = (x0,y1,z0)
    v001 = (x0,y0,z1); v101 = (x1,y0,z1); v111 = (x1,y1,z1); v011 = (x0,y1,z1)
    faces = [
        (v000,v100,v110,texture),
        (v001,v011,v111,texture),
        (v100,v101,v111,texture),
        (v001,v000,v010,texture),
        (v010,v110,v111,texture),
        (v000,v001,v101,texture)
    ]
    return faces

class Brush:
    def __init__(self, faces):
        self.faces = faces

class Entity:
    def __init__(self, classname, properties=None, brushes=None):
        self.classname = classname
        self.properties = properties or {}
        self.brushes = brushes or []

class QuakeMap:
    def __init__(self):
        self.entities = []
        self.textures = DEFAULT_TEXTURES.copy()
        self.items = DEFAULT_ITEMS.copy()
        self.new_map()

    def new_map(self):
        self.entities = [Entity("worldspawn", properties={"wad": r"C:\quake\TEX.WAD"})]
        print("New map created with worldspawn.")

    def add_brush_box(self,cx,cy,cz,sx,sy,sz,texture="bricka2_2"):
        hx,hy,hz = sx/2,sy/2,sz/2
        minp,maxp = (cx-hx,cy-hy,cz-hz),(cx+hx,cy+hy,cz+hz)
        faces = box_faces(minp,maxp,texture)
        self.entities[0].brushes.append(Brush(faces))
        print(f"Box added at ({cx},{cy},{cz}) size=({sx},{sy},{sz}) tex={texture}")

    def add_room(self,cx,cy,cz,width,depth,height,wall_tex=None,floor_tex=None,ceil_tex=None):
        wall_tex = wall_tex or "bricka2_2"
        floor_tex = floor_tex or "woodflr1_5"
        ceil_tex = ceil_tex or "sky1"
        wt = 32
        self.add_brush_box(cx,cy,cz-height/2+wt/2,width+2*wt,depth+2*wt,wt,floor_tex)
        self.add_brush_box(cx,cy,cz+height/2-wt/2,width+2*wt,depth+2*wt,wt,ceil_tex)
        self.add_brush_box(cx,cy+depth/2-wt/2,cz,width,wt,height,wall_tex)
        self.add_brush_box(cx,cy-depth/2+wt/2,cz,width,wt,height,wall_tex)
        self.add_brush_box(cx+width/2-wt/2,cy,cz,wt,depth,height,wall_tex)
        self.add_brush_box(cx-width/2+wt/2,cy,cz,wt,depth,height,wall_tex)
        print(f"Room added at ({cx},{cy},{cz}) size=({width},{depth},{height})")

    def add_entity(self,classname,**properties):
        if "origin" in properties: properties["origin"]=str(properties["origin"])
        if classname.startswith("monster") and "angle" not in properties: properties["angle"]="0"
        if classname=="info_player_start" and "angle" not in properties: properties["angle"]="0"
        if classname=="light" and "angle" not in properties: properties["angle"]="360"
        self.entities.append(Entity(classname,properties))
        print(f"Entity '{classname}' added with properties: {properties}")

    def add_item(self,classname,x,y,z,**extra):
        props={"origin":f"{x} {y} {z}"}
        props.update(extra)
        self.add_entity(classname,**props)

    def add_light(self,x,y,z,intensity=300):
        self.add_entity("light",origin=f"{x} {y} {z}",light=str(intensity))

    def add_player(self,x,y,z,angle=0):
        self.add_entity("info_player_start",origin=f"{x} {y} {z}",angle=str(angle))

    def list_textures(self):
        print("Example Textures:")
        for tex in self.textures: print("  "+tex)

    def list_items(self):
        print("Example Quake items/entities:")
        for itm in self.items: print("  "+itm)

    def export_map(self,filename):
        with open(filename,"w",encoding="utf-8") as f:
            f.write("// Generated by QSpawn Sheikh's Quake MAP Creator Beta 1.1\n")
            for ent in self.entities:
                f.write("{\n")
                f.write(f' "classname" "{ent.classname}"\n')
                for k,v in ent.properties.items():
                    f.write(f' "{k}" "{v}"\n')
                for br in ent.brushes:
                    f.write(" {\n")
                    for a,b,c,tex in br.faces:
                        f.write("  "+face_line(a,b,c,tex)+"\n")
                    f.write(" }\n")
                f.write("}\n\n")
        print(f"Map exported -> {filename}")

def main():
    print_banner()
    qmap=QuakeMap()
    while True:
        try: cmd=input("quake> ").strip()
        except (EOFError,KeyboardInterrupt): print(); break
        if not cmd: continue
        parts=cmd.split()
        c=parts[0].upper()
        try:
            if c=="HELP":
                print("""
Commands:
  NEW
  ROOM cx cy cz width depth height [WALL=wall_tex FLOOR=floor_tex CEIL=ceil_tex]
  BOX cx cy cz sx sy sz TEXTURE=tex
  LIGHT x y z [intensity]
  PLAYER x y z [angle]
  ENTITY classname x y z [key=value ...]
  ITEM classname x y z [key=value ...]
  TEXTURES
  ITEMS
  EXPORT filename.map
  EXIT
""")
            elif c in ["EXIT","QUIT"]: break
            elif c=="TEXTURES": qmap.list_textures()
            elif c=="ITEMS": qmap.list_items()
            elif c=="NEW": qmap.new_map()
            elif c=="ROOM":
                if len(parts)<7: print("Usage: ROOM cx cy cz width depth height [WALL=wall_tex FLOOR=floor_tex CEIL=ceil_tex]")
                else:
                    cx,cy,cz=map(int,parts[1:4])
                    w,d,h=map(int,parts[4:7])
                    wall=floor=ceil=None
                    for p in parts[7:]:
                        if p.upper().startswith("WALL="): wall=p[5:]
                        if p.upper().startswith("FLOOR="): floor=p[6:]
                        if p.upper().startswith("CEIL="): ceil=p[5:]
                    qmap.add_room(cx,cy,cz,w,d,h,wall_tex=wall,floor_tex=floor,ceil_tex=ceil)
            elif c=="BOX":
                if len(parts)<7: print("Usage: BOX cx cy cz sx sy sz TEXTURE=tex")
                else:
                    cx,cy,cz=map(int,parts[1:4])
                    sx,sy,sz=map(int,parts[4:7])
                    tex="bricka2_2"
                    for p in parts[7:]:
                        if p.upper().startswith("TEXTURE="): tex=p[8:]
                    qmap.add_brush_box(cx,cy,cz,sx,sy,sz,texture=tex)
            elif c=="LIGHT":
                if len(parts)<4: print("Usage: LIGHT x y z [intensity]")
                else:
                    x,y,z=map(int,parts[1:4])
                    inten=int(parts[4]) if len(parts)>4 else 300
                    qmap.add_light(x,y,z,intensity=inten)
            elif c=="PLAYER":
                if len(parts)<4: print("Usage: PLAYER x y z [angle]")
                else:
                    x,y,z=map(int,parts[1:4])
                    ang=int(parts[4]) if len(parts)>4 else 0
                    qmap.add_player(x,y,z,angle=ang)
            elif c=="ENTITY":
                if len(parts)<5: print("Usage: ENTITY classname x y z [key=value ...]")
                else:
                    classname=parts[1]
                    x,y,z=map(int,parts[2:5])
                    props={"origin":f"{x} {y} {z}"}
                    for kv in parts[5:]:
                        if "=" in kv: k,v=kv.split("=",1); props[k]=v
                    qmap.add_entity(classname,**props)
            elif c=="ITEM":
                if len(parts)<5: print("Usage: ITEM classname x y z [key=value ...]")
                else:
                    classname=parts[1]; x,y,z=map(int,parts[2:5]); props={}
                    for kv in parts[5:]:
                        if "=" in kv: k,v=kv.split("=",1); props[k]=v
                    qmap.add_item(classname,x,y,z,**props)
            elif c=="EXPORT":
                if len(parts)<2: print("Usage: EXPORT filename.map")
                else: qmap.export_map(parts[1])
            else: print("Unknown command. Type HELP.")
        except Exception as e:
            print("ERROR:",e)

if __name__=="__main__": main()
